// Code generated by fastssz. DO NOT EDIT.
// Hash: 17d4c9180818d70e873edf284079b326d586a16686d17c7c974a8a2fd19ec3e9
// Version: 0.1.3
package electra

import (
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BeaconBlock object
func (b *BeaconBlock) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconBlock object to a target array
func (b *BeaconBlock) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	// Fixed portion: slot(8) + proposer_index(8) + parent_root(32) + state_root(32) + proposer_tee_type(1) + proposer_tee_quote(8192) + offset(4) = 8277
	offset := int(8277)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	dst = append(dst, b.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, b.StateRoot[:]...)

	// Field (4) 'ProposerTEEType'
	dst = append(dst, byte(b.ProposerTEEType))

	// Field (5) 'ProposerTEEQuote'
	dst = append(dst, b.ProposerTEEQuote[:]...)

	// Offset (6) 'Body'
	dst = ssz.WriteOffset(dst, offset)
	if b.Body == nil {
		b.Body = new(BeaconBlockBody)
	}
	offset += b.Body.SizeSSZ()

	// Field (6) 'Body'
	if dst, err = b.Body.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconBlock object
func (b *BeaconBlock) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	// Minimum size: slot(8) + proposer_index(8) + parent_root(32) + state_root(32) + proposer_tee_type(1) + proposer_tee_quote(8192) + offset(4) = 8277
	const minSize = 8277
	if size < minSize {
		return ssz.ErrSize
	}

	tail := buf
	var o6 uint64

	// Field (0) 'Slot'
	b.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'ProposerIndex'
	b.ProposerIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[8:16]))

	// Field (2) 'ParentRoot'
	copy(b.ParentRoot[:], buf[16:48])

	// Field (3) 'StateRoot'
	copy(b.StateRoot[:], buf[48:80])

	// Field (4) 'ProposerTEEType'
	b.ProposerTEEType = uint8(buf[80])

	// Field (5) 'ProposerTEEQuote'
	copy(b.ProposerTEEQuote[:], buf[81:81+phase0.ProposerTEEQuoteLength])

	// Offset (6) 'Body' - at position 81 + 8192 = 8273
	if o6 = ssz.ReadOffset(buf[8273:8277]); o6 > size {
		return ssz.ErrOffset
	}

	if o6 < minSize {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (6) 'Body'
	{
		buf = tail[o6:]
		if b.Body == nil {
			b.Body = new(BeaconBlockBody)
		}
		if err = b.Body.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconBlock object
func (b *BeaconBlock) SizeSSZ() (size int) {
	// Fixed portion: slot(8) + proposer_index(8) + parent_root(32) + state_root(32) + proposer_tee_type(1) + proposer_tee_quote(8192) + offset(4) = 8277
	size = 8277

	// Field (6) 'Body'
	if b.Body == nil {
		b.Body = new(BeaconBlockBody)
	}
	size += b.Body.SizeSSZ()

	return
}

// HashTreeRoot ssz hashes the BeaconBlock object
func (b *BeaconBlock) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconBlock object with a hasher
func (b *BeaconBlock) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	hh.PutUint64(uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	hh.PutBytes(b.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(b.StateRoot[:])

	// Field (4) 'ProposerTEEType'
	hh.PutUint64(uint64(b.ProposerTEEType))

	// Field (5) 'ProposerTEEQuote'
	hh.PutBytes(b.ProposerTEEQuote[:])

	// Field (6) 'Body'
	if err = b.Body.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BeaconBlock object
func (b *BeaconBlock) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
