// Code generated by fastssz. DO NOT EDIT.
// Hash: adabd63e74fd1d7901414007d2d918638b3a939bb92180df274f553891838d1e
// Version: 0.1.3
package electra

import (
	"fmt"

	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/capella"
	"github.com/attestantio/go-eth2-client/spec/deneb"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BeaconState object
func (b *BeaconState) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconState object to a target array
func (b *BeaconState) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, b.GenesisTime)

	// Field (1) 'GenesisValidatorsRoot'
	dst = append(dst, b.GenesisValidatorsRoot[:]...)

	// Field (2) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(phase0.Fork)
	}
	if dst, err = b.Fork.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(phase0.BeaconBlockHeader)
	}
	if dst, err = b.LatestBlockHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (5) 'BlockRoots'
	if size := len(b.BlockRoots); size != 8192 {
		err = ssz.ErrVectorLengthFn("BeaconState.BlockRoots", size, 8192)
		return
	}
	for ii := 0; ii < 8192; ii++ {
		dst = append(dst, b.BlockRoots[ii][:]...)
	}

	// Field (6) 'StateRoots'
	if size := len(b.StateRoots); size != 8192 {
		err = ssz.ErrVectorLengthFn("BeaconState.StateRoots", size, 8192)
		return
	}
	for ii := 0; ii < 8192; ii++ {
		dst = append(dst, b.StateRoots[ii][:]...)
	}

	// Calculate offset dynamically based on actual header size
	// Offset points to where variable-length data starts (after ALL fixed-length fields)
	// First, calculate size up to where offsets are written:
	// genesis_time(8) + genesis_validators_root(32) + slot(8) + fork(16) + header(variable) + BlockRoots(8192*32) + StateRoots(8192*32)
	fixedPortionBeforeOffsets := 8 + 32 + 8 + 16               // genesis_time + genesis_validators_root + slot + fork
	fixedPortionBeforeOffsets += b.LatestBlockHeader.SizeSSZ() // Actual header size (8305 for TEE, 112 for legacy)
	fixedPortionBeforeOffsets += 8192 * 32                     // BlockRoots
	fixedPortionBeforeOffsets += 8192 * 32                     // StateRoots

	// Now calculate size of offsets section (one offset per variable-length field)
	// Offsets for: HistoricalRoots, ETH1DataVotes, Validators, Balances, PreviousEpochParticipation, CurrentEpochParticipation, InactivityScores, LatestExecutionPayloadHeader, HistoricalSummaries, PendingDeposits, PendingPartialWithdrawals, PendingConsolidations
	numOffsets := 12
	offsetsSize := numOffsets * 4 // Each offset is 4 bytes

	// Calculate size of fixed fields that come AFTER offsets:
	// ETH1Data(72) + ETH1DepositIndex(8) + RANDAOMixes(65536*32) + Slashings(8192*8) + JustificationBits(1) +
	// PreviousJustifiedCheckpoint(40) + CurrentJustifiedCheckpoint(40) + FinalizedCheckpoint(40) +
	// CurrentSyncCommittee(24624) + NextSyncCommittee(24624) + NextWithdrawalIndex(8) + NextWithdrawalValidatorIndex(8) +
	// DepositRequestsStartIndex(8) + DepositBalanceToConsume(8) + ExitBalanceToConsume(8) + EarliestExitEpoch(8) +
	// ConsolidationBalanceToConsume(8) + EarliestConsolidationEpoch(8)
	fixedPortionAfterOffsets := 72         // ETH1Data
	fixedPortionAfterOffsets += 8          // ETH1DepositIndex
	fixedPortionAfterOffsets += 65536 * 32 // RANDAOMixes
	fixedPortionAfterOffsets += 8192 * 8   // Slashings
	fixedPortionAfterOffsets += 1          // JustificationBits
	fixedPortionAfterOffsets += 40         // PreviousJustifiedCheckpoint
	fixedPortionAfterOffsets += 40         // CurrentJustifiedCheckpoint
	fixedPortionAfterOffsets += 40         // FinalizedCheckpoint
	fixedPortionAfterOffsets += 24624      // CurrentSyncCommittee
	fixedPortionAfterOffsets += 24624      // NextSyncCommittee
	fixedPortionAfterOffsets += 8          // NextWithdrawalIndex
	fixedPortionAfterOffsets += 8          // NextWithdrawalValidatorIndex
	fixedPortionAfterOffsets += 8          // DepositRequestsStartIndex
	fixedPortionAfterOffsets += 8          // DepositBalanceToConsume
	fixedPortionAfterOffsets += 8          // ExitBalanceToConsume
	fixedPortionAfterOffsets += 8          // EarliestExitEpoch
	fixedPortionAfterOffsets += 8          // ConsolidationBalanceToConsume
	fixedPortionAfterOffsets += 8          // EarliestConsolidationEpoch

	// Total fixed portion size = before offsets + offsets + after offsets
	totalFixedPortionSize := fixedPortionBeforeOffsets + offsetsSize + fixedPortionAfterOffsets
	offset := int(totalFixedPortionSize)

	// Offset (7) 'HistoricalRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.HistoricalRoots) * 32

	// Field (8) 'ETH1Data'
	if b.ETH1Data == nil {
		b.ETH1Data = new(phase0.ETH1Data)
	}
	if dst, err = b.ETH1Data.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (9) 'ETH1DataVotes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.ETH1DataVotes) * 72

	// Field (10) 'ETH1DepositIndex'
	dst = ssz.MarshalUint64(dst, b.ETH1DepositIndex)

	// Offset (11) 'Validators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Validators) * 121

	// Offset (12) 'Balances'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Balances) * 8

	// Field (13) 'RANDAOMixes'
	if size := len(b.RANDAOMixes); size != 65536 {
		err = ssz.ErrVectorLengthFn("BeaconState.RANDAOMixes", size, 65536)
		return
	}
	for ii := 0; ii < 65536; ii++ {
		dst = append(dst, b.RANDAOMixes[ii][:]...)
	}

	// Field (14) 'Slashings'
	if size := len(b.Slashings); size != 8192 {
		err = ssz.ErrVectorLengthFn("BeaconState.Slashings", size, 8192)
		return
	}
	for ii := 0; ii < 8192; ii++ {
		dst = ssz.MarshalUint64(dst, uint64(b.Slashings[ii]))
	}

	// Offset (15) 'PreviousEpochParticipation'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PreviousEpochParticipation) * 1

	// Offset (16) 'CurrentEpochParticipation'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.CurrentEpochParticipation) * 1

	// Field (17) 'JustificationBits'
	if size := len(b.JustificationBits); size != 1 {
		err = ssz.ErrBytesLengthFn("BeaconState.JustificationBits", size, 1)
		return
	}
	dst = append(dst, b.JustificationBits...)

	// Field (18) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if dst, err = b.PreviousJustifiedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if dst, err = b.CurrentJustifiedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (20) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(phase0.Checkpoint)
	}
	if dst, err = b.FinalizedCheckpoint.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (21) 'InactivityScores'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.InactivityScores) * 8

	// Field (22) 'CurrentSyncCommittee'
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(altair.SyncCommittee)
	}
	if dst, err = b.CurrentSyncCommittee.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (23) 'NextSyncCommittee'
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(altair.SyncCommittee)
	}
	if dst, err = b.NextSyncCommittee.MarshalSSZTo(dst); err != nil {
		return
	}

	// Offset (24) 'LatestExecutionPayloadHeader'
	dst = ssz.WriteOffset(dst, offset)
	if b.LatestExecutionPayloadHeader == nil {
		b.LatestExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	offset += b.LatestExecutionPayloadHeader.SizeSSZ()

	// Field (25) 'NextWithdrawalIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.NextWithdrawalIndex))

	// Field (26) 'NextWithdrawalValidatorIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.NextWithdrawalValidatorIndex))

	// Offset (27) 'HistoricalSummaries'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.HistoricalSummaries) * 64

	// Field (28) 'DepositReceiptsStartIndex'
	dst = ssz.MarshalUint64(dst, b.DepositRequestsStartIndex)

	// Field (29) 'DepositBalanceToConsume'
	dst = ssz.MarshalUint64(dst, uint64(b.DepositBalanceToConsume))

	// Field (30) 'ExitBalanceToConsume'
	dst = ssz.MarshalUint64(dst, uint64(b.ExitBalanceToConsume))

	// Field (31) 'EarliestExitEpoch'
	dst = ssz.MarshalUint64(dst, uint64(b.EarliestExitEpoch))

	// Field (32) 'ConsolidationBalanceToConsume'
	dst = ssz.MarshalUint64(dst, uint64(b.ConsolidationBalanceToConsume))

	// Field (33) 'EarliestConsolidationEpoch'
	dst = ssz.MarshalUint64(dst, uint64(b.EarliestConsolidationEpoch))

	// Offset (34) 'PendingBalanceDeposits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingDeposits) * 192

	// Offset (35) 'PendingPartialWithdrawals'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingPartialWithdrawals) * 24

	// Offset (36) 'PendingConsolidations'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.PendingConsolidations) * 16

	// Field (7) 'HistoricalRoots'
	if size := len(b.HistoricalRoots); size > 16777216 {
		err = ssz.ErrListTooBigFn("BeaconState.HistoricalRoots", size, 16777216)
		return
	}
	for ii := 0; ii < len(b.HistoricalRoots); ii++ {
		dst = append(dst, b.HistoricalRoots[ii][:]...)
	}

	// Field (9) 'ETH1DataVotes'
	if size := len(b.ETH1DataVotes); size > 2048 {
		err = ssz.ErrListTooBigFn("BeaconState.ETH1DataVotes", size, 2048)
		return
	}
	for ii := 0; ii < len(b.ETH1DataVotes); ii++ {
		if dst, err = b.ETH1DataVotes[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (11) 'Validators'
	if size := len(b.Validators); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.Validators", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.Validators); ii++ {
		if dst, err = b.Validators[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (12) 'Balances'
	if size := len(b.Balances); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.Balances", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.Balances); ii++ {
		dst = ssz.MarshalUint64(dst, uint64(b.Balances[ii]))
	}

	// Field (15) 'PreviousEpochParticipation'
	if size := len(b.PreviousEpochParticipation); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.PreviousEpochParticipation", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.PreviousEpochParticipation); ii++ {
		dst = ssz.MarshalUint8(dst, uint8(b.PreviousEpochParticipation[ii]))
	}

	// Field (16) 'CurrentEpochParticipation'
	if size := len(b.CurrentEpochParticipation); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.CurrentEpochParticipation", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.CurrentEpochParticipation); ii++ {
		dst = ssz.MarshalUint8(dst, uint8(b.CurrentEpochParticipation[ii]))
	}

	// Field (21) 'InactivityScores'
	if size := len(b.InactivityScores); size > 1099511627776 {
		err = ssz.ErrListTooBigFn("BeaconState.InactivityScores", size, 1099511627776)
		return
	}
	for ii := 0; ii < len(b.InactivityScores); ii++ {
		dst = ssz.MarshalUint64(dst, b.InactivityScores[ii])
	}

	// Field (24) 'LatestExecutionPayloadHeader'
	if dst, err = b.LatestExecutionPayloadHeader.MarshalSSZTo(dst); err != nil {
		return
	}

	// Field (27) 'HistoricalSummaries'
	if size := len(b.HistoricalSummaries); size > 16777216 {
		err = ssz.ErrListTooBigFn("BeaconState.HistoricalSummaries", size, 16777216)
		return
	}
	for ii := 0; ii < len(b.HistoricalSummaries); ii++ {
		if dst, err = b.HistoricalSummaries[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (34) 'PendingBalanceDeposits'
	if size := len(b.PendingDeposits); size > 134217728 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingBalanceDeposits", size, 134217728)
		return
	}
	for ii := 0; ii < len(b.PendingDeposits); ii++ {
		if dst, err = b.PendingDeposits[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (35) 'PendingPartialWithdrawals'
	if size := len(b.PendingPartialWithdrawals); size > 134217728 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingPartialWithdrawals", size, 134217728)
		return
	}
	for ii := 0; ii < len(b.PendingPartialWithdrawals); ii++ {
		if dst, err = b.PendingPartialWithdrawals[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (36) 'PendingConsolidations'
	if size := len(b.PendingConsolidations); size > 262144 {
		err = ssz.ErrListTooBigFn("BeaconState.PendingConsolidations", size, 262144)
		return
	}
	for ii := 0; ii < len(b.PendingConsolidations); ii++ {
		if dst, err = b.PendingConsolidations[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconState object
func (b *BeaconState) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Starting unmarshal, buffer size: %d bytes\n", size)
	if size < 2736713 {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Buffer too small: %d < 2736713\n", size)
		return ssz.ErrSize
	}

	tail := buf
	var o7, o9, o11, o12, o15, o16, o21, o24, o27, o34, o35, o36 uint64

	// Field (0) 'GenesisTime'
	b.GenesisTime = ssz.UnmarshallUint64(buf[0:8])
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: GenesisTime: %d\n", b.GenesisTime)

	// Field (1) 'GenesisValidatorsRoot'
	copy(b.GenesisValidatorsRoot[:], buf[8:40])
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: GenesisValidatorsRoot: %x\n", b.GenesisValidatorsRoot[:])

	// Field (2) 'Slot'
	b.Slot = phase0.Slot(ssz.UnmarshallUint64(buf[40:48]))
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Slot: %d\n", b.Slot)

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(phase0.Fork)
	}
	if err = b.Fork.UnmarshalSSZ(buf[48:64]); err != nil {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Failed to unmarshal Fork at offset 48-64: %v\n", err)
		return err
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Fork unmarshaled successfully\n")

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(phase0.BeaconBlockHeader)
	}

	// Detect header size: try extended header first (8305 bytes), fallback to legacy (112 bytes)
	headerStart := 64
	extendedHeaderSize := 112 + 1 + phase0.ProposerTEEQuoteLength // Extended header size (8305)
	legacyHeaderSize := 112

	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Header detection - start: %d, extended: %d, legacy: %d, buffer len: %d\n",
		headerStart, extendedHeaderSize, legacyHeaderSize, len(buf))

	var headerSize int
	if headerStart+extendedHeaderSize <= len(buf) {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Attempting extended header unmarshal (size: %d)\n", extendedHeaderSize)
		// Try to unmarshal with extended size to see if it's valid
		tempHeader := &phase0.BeaconBlockHeader{}
		// Create a slice of exactly the right size for the header
		headerBuf := make([]byte, extendedHeaderSize)
		copy(headerBuf, buf[headerStart:headerStart+extendedHeaderSize])
		if err = tempHeader.UnmarshalSSZ(headerBuf); err == nil {
			// Extended header worked
			fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Extended header unmarshaled successfully (size: %d)\n", extendedHeaderSize)
			fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Header TEE type: %d, TEE quote first 16 bytes: %x\n",
				tempHeader.ProposerTEEType, tempHeader.ProposerTEEQuote[:16])
			headerSize = extendedHeaderSize
			b.LatestBlockHeader = tempHeader
		} else {
			// Fallback to legacy size
			fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Extended header unmarshal failed: %v, falling back to legacy\n", err)
			headerSize = legacyHeaderSize
		}
	} else {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Buffer too small for extended header, using legacy (available: %d, needed: %d)\n",
			len(buf)-headerStart, extendedHeaderSize)
		headerSize = legacyHeaderSize
	}

	// If we haven't unmarshaled yet (legacy case), do it now
	if headerSize == legacyHeaderSize {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Unmarshaling legacy header (size: %d)\n", legacyHeaderSize)
		headerBuf := make([]byte, legacyHeaderSize)
		copy(headerBuf, buf[headerStart:headerStart+legacyHeaderSize])
		if err = b.LatestBlockHeader.UnmarshalSSZ(headerBuf); err != nil {
			fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Legacy header unmarshal failed: %v\n", err)
			return err
		}
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Legacy header unmarshaled successfully\n")
	}

	headerEnd := headerStart + headerSize
	headerSizeDiff := headerSize - legacyHeaderSize // Difference from legacy size
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Header size: %d, headerEnd: %d, headerSizeDiff: %d\n",
		headerSize, headerEnd, headerSizeDiff)

	// Field (5) 'BlockRoots'
	blockRootsStart := headerEnd
	blockRootsEnd := blockRootsStart + 8192*32
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: BlockRoots range: %d-%d (size: %d)\n",
		blockRootsStart, blockRootsEnd, blockRootsEnd-blockRootsStart)
	if blockRootsEnd > len(buf) {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - BlockRoots end (%d) exceeds buffer size (%d)\n",
			blockRootsEnd, len(buf))
		return fmt.Errorf("blockRootsEnd (%d) exceeds buffer size (%d)", blockRootsEnd, len(buf))
	}
	b.BlockRoots = make([]phase0.Root, 8192)
	for ii := 0; ii < 8192; ii++ {
		copy(b.BlockRoots[ii][:], buf[blockRootsStart:blockRootsEnd][ii*32:(ii+1)*32])
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: BlockRoots unmarshaled successfully\n")

	// Field (6) 'StateRoots'
	stateRootsStart := blockRootsEnd
	stateRootsEnd := stateRootsStart + 8192*32
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: StateRoots range: %d-%d (size: %d)\n",
		stateRootsStart, stateRootsEnd, stateRootsEnd-stateRootsStart)
	if stateRootsEnd > len(buf) {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - StateRoots end (%d) exceeds buffer size (%d)\n",
			stateRootsEnd, len(buf))
		return fmt.Errorf("stateRootsEnd (%d) exceeds buffer size (%d)", stateRootsEnd, len(buf))
	}
	b.StateRoots = make([]phase0.Root, 8192)
	for ii := 0; ii < 8192; ii++ {
		copy(b.StateRoots[ii][:], buf[stateRootsStart:stateRootsEnd][ii*32:(ii+1)*32])
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: StateRoots unmarshaled successfully\n")

	// Offset (7) 'HistoricalRoots'
	// Offset section starts after StateRoots
	offsetsStart := stateRootsEnd
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Offsets start at: %d\n", offsetsStart)

	// Check if offsets might be stored at legacy position (if SSZ was encoded with legacy header)
	legacyStateRootsEnd := 64 + legacyHeaderSize + 8192*32 + 8192*32 // 524464
	legacyOffsetsStart := legacyStateRootsEnd
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Legacy offsets would start at: %d, current: %d, diff: %d\n",
		legacyOffsetsStart, offsetsStart, offsetsStart-legacyOffsetsStart)

	// Try reading offset from both positions to detect which one is correct
	o7FromCurrent := ssz.ReadOffset(buf[offsetsStart : offsetsStart+4])
	o7FromLegacy := ssz.ReadOffset(buf[legacyOffsetsStart : legacyOffsetsStart+4])
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: o7 from current pos (%d): %d, from legacy pos (%d): %d\n",
		offsetsStart, o7FromCurrent, legacyOffsetsStart, o7FromLegacy)

	// Determine which offset position is correct based on validity
	// If SSZ was encoded with legacy header but we're decoding with extended, offsets are at legacy position
	var actualOffsetsStart int
	if headerSizeDiff > 0 && o7FromLegacy < size && o7FromLegacy > 0 && (o7FromCurrent > size || o7FromCurrent == 0) {
		// Offsets are stored at legacy position
		actualOffsetsStart = legacyOffsetsStart
		o7 = o7FromLegacy
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Using legacy offset position (SSZ encoded with legacy header)\n")
	} else {
		// Offsets are stored at current position
		actualOffsetsStart = offsetsStart
		o7 = o7FromCurrent
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Using current offset position\n")
	}

	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Offset o7 raw value: %d (0x%x), headerSizeDiff: %d, actualOffsetsStart: %d\n",
		o7, o7, headerSizeDiff, actualOffsetsStart)

	// If SSZ was encoded with legacy header but we have extended header, adjust offset values
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o7 = o7 + uint64(headerSizeDiff)
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Adjusted o7 by adding headerSizeDiff: %d\n", headerSizeDiff)
	}

	if o7 > size {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - Offset o7 (%d) exceeds buffer size (%d)\n", o7, size)
		return ssz.ErrOffset
	}

	// Calculate minimum expected offset based on actual header size
	// Fixed portion: genesis(8) + root(32) + slot(8) + fork(16) + header(variable) + blockRoots(262144) + stateRoots(262144) + offsets(48) + fixed fields after offsets
	fixedPortionBeforeOffsets := 8 + 32 + 8 + 16 + headerSize + 8192*32 + 8192*32
	fixedPortionAfterOffsets := 72 + 8 + 65536*32 + 8192*8 + 1 + 40 + 40 + 40 + 24624 + 24624 + 8 + 8 + 8 + 8 + 8 + 8 + 8 + 8
	minExpectedOffset := uint64(fixedPortionBeforeOffsets + 12*4 + fixedPortionAfterOffsets)
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Offset o7 (HistoricalRoots): %d, min expected: %d (headerSize: %d)\n",
		o7, minExpectedOffset, headerSize)

	if o7 < minExpectedOffset {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - Invalid variable offset: o7 (%d) < min (%d)\n",
			o7, minExpectedOffset)
		return ssz.ErrInvalidVariableOffset
	}

	// Field (8) 'ETH1Data'
	// ETH1Data starts after 12 offsets (48 bytes) from the actual offsets start position
	eth1DataStart := actualOffsetsStart + 12*4
	eth1DataEnd := eth1DataStart + 72
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ETH1Data range: %d-%d\n", eth1DataStart, eth1DataEnd)
	if eth1DataEnd > len(buf) {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - ETH1Data end (%d) exceeds buffer size (%d)\n",
			eth1DataEnd, len(buf))
		return fmt.Errorf("eth1DataEnd (%d) exceeds buffer size (%d)", eth1DataEnd, len(buf))
	}
	if b.ETH1Data == nil {
		b.ETH1Data = new(phase0.ETH1Data)
	}
	if err = b.ETH1Data.UnmarshalSSZ(buf[eth1DataStart:eth1DataEnd]); err != nil {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Failed to unmarshal ETH1Data: %v\n", err)
		return err
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ETH1Data unmarshaled successfully\n")

	// Offset (9) 'ETH1DataVotes'
	eth1DataVotesOffsetStart := eth1DataEnd
	o9Raw := ssz.ReadOffset(buf[eth1DataVotesOffsetStart : eth1DataVotesOffsetStart+4])
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Offset o9 raw value: %d (0x%x) at position %d\n",
		o9Raw, o9Raw, eth1DataVotesOffsetStart)

	// Adjust offset if SSZ was encoded with legacy header
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o9 = o9Raw + uint64(headerSizeDiff)
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Adjusted o9 from %d to %d (added %d)\n", o9Raw, o9, headerSizeDiff)
	} else {
		o9 = o9Raw
	}

	if o9 > size || o7 > o9 {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - Invalid offset o9: %d (raw: %d, size: %d, o7: %d)\n",
			o9, o9Raw, size, o7)
		return ssz.ErrOffset
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Offset o9 (ETH1DataVotes): %d\n", o9)

	// Field (10) 'ETH1DepositIndex'
	eth1DepositIndexStart := eth1DataVotesOffsetStart + 4
	b.ETH1DepositIndex = ssz.UnmarshallUint64(buf[eth1DepositIndexStart : eth1DepositIndexStart+8])

	// Offset (11) 'Validators'
	validatorsOffsetStart := eth1DepositIndexStart + 8
	o11Raw := ssz.ReadOffset(buf[validatorsOffsetStart : validatorsOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o11 = o11Raw + uint64(headerSizeDiff)
	} else {
		o11 = o11Raw
	}
	if o11 > size || o9 > o11 {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - Invalid offset o11: %d (raw: %d, size: %d, o9: %d)\n", o11, o11Raw, size, o9)
		return ssz.ErrOffset
	}

	// Offset (12) 'Balances'
	balancesOffsetStart := validatorsOffsetStart + 4
	o12Raw := ssz.ReadOffset(buf[balancesOffsetStart : balancesOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o12 = o12Raw + uint64(headerSizeDiff)
	} else {
		o12 = o12Raw
	}
	if o12 > size || o11 > o12 {
		fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: ERROR - Invalid offset o12: %d (raw: %d, size: %d, o11: %d)\n", o12, o12Raw, size, o11)
		return ssz.ErrOffset
	}

	// Field (13) 'RANDAOMixes'
	randaoMixesStart := balancesOffsetStart + 4
	randaoMixesEnd := randaoMixesStart + 65536*32
	b.RANDAOMixes = make([]phase0.Root, 65536)
	for ii := 0; ii < 65536; ii++ {
		copy(b.RANDAOMixes[ii][:], buf[randaoMixesStart:randaoMixesEnd][ii*32:(ii+1)*32])
	}

	// Field (14) 'Slashings'
	slashingsStart := randaoMixesEnd
	slashingsEnd := slashingsStart + 8192*8
	b.Slashings = make([]phase0.Gwei, 8192)
	for ii := 0; ii < 8192; ii++ {
		b.Slashings[ii] = phase0.Gwei(ssz.UnmarshallUint64(buf[slashingsStart:slashingsEnd][ii*8 : (ii+1)*8]))
	}

	// Offset (15) 'PreviousEpochParticipation'
	prevEpochPartOffsetStart := slashingsEnd
	o15Raw := ssz.ReadOffset(buf[prevEpochPartOffsetStart : prevEpochPartOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o15 = o15Raw + uint64(headerSizeDiff)
	} else {
		o15 = o15Raw
	}
	if o15 > size || o12 > o15 {
		return ssz.ErrOffset
	}

	// Offset (16) 'CurrentEpochParticipation'
	currEpochPartOffsetStart := prevEpochPartOffsetStart + 4
	o16Raw := ssz.ReadOffset(buf[currEpochPartOffsetStart : currEpochPartOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o16 = o16Raw + uint64(headerSizeDiff)
	} else {
		o16 = o16Raw
	}
	if o16 > size || o15 > o16 {
		return ssz.ErrOffset
	}

	// Field (17) 'JustificationBits'
	justificationBitsStart := currEpochPartOffsetStart + 4
	if cap(b.JustificationBits) == 0 {
		b.JustificationBits = make([]byte, 0, 1)
	}
	b.JustificationBits = append(b.JustificationBits, buf[justificationBitsStart:justificationBitsStart+1]...)

	// Field (18) 'PreviousJustifiedCheckpoint'
	prevJustifiedStart := justificationBitsStart + 1
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.PreviousJustifiedCheckpoint.UnmarshalSSZ(buf[prevJustifiedStart : prevJustifiedStart+40]); err != nil {
		return err
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	currJustifiedStart := prevJustifiedStart + 40
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.CurrentJustifiedCheckpoint.UnmarshalSSZ(buf[currJustifiedStart : currJustifiedStart+40]); err != nil {
		return err
	}

	// Field (20) 'FinalizedCheckpoint'
	finalizedStart := currJustifiedStart + 40
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.FinalizedCheckpoint.UnmarshalSSZ(buf[finalizedStart : finalizedStart+40]); err != nil {
		return err
	}

	// Offset (21) 'InactivityScores'
	inactivityScoresOffsetStart := finalizedStart + 40
	o21Raw := ssz.ReadOffset(buf[inactivityScoresOffsetStart : inactivityScoresOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o21 = o21Raw + uint64(headerSizeDiff)
	} else {
		o21 = o21Raw
	}
	if o21 > size || o16 > o21 {
		return ssz.ErrOffset
	}

	// Field (22) 'CurrentSyncCommittee'
	currentSyncCommitteeStart := inactivityScoresOffsetStart + 4
	currentSyncCommitteeEnd := currentSyncCommitteeStart + 24624
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(altair.SyncCommittee)
	}
	if err = b.CurrentSyncCommittee.UnmarshalSSZ(buf[currentSyncCommitteeStart:currentSyncCommitteeEnd]); err != nil {
		return err
	}

	// Field (23) 'NextSyncCommittee'
	nextSyncCommitteeStart := currentSyncCommitteeEnd
	nextSyncCommitteeEnd := nextSyncCommitteeStart + 24624
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(altair.SyncCommittee)
	}
	if err = b.NextSyncCommittee.UnmarshalSSZ(buf[nextSyncCommitteeStart:nextSyncCommitteeEnd]); err != nil {
		return err
	}

	// Offset (24) 'LatestExecutionPayloadHeader'
	latestExecPayloadOffsetStart := nextSyncCommitteeEnd
	o24Raw := ssz.ReadOffset(buf[latestExecPayloadOffsetStart : latestExecPayloadOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o24 = o24Raw + uint64(headerSizeDiff)
	} else {
		o24 = o24Raw
	}
	if o24 > size || o21 > o24 {
		return ssz.ErrOffset
	}

	// Field (25) 'NextWithdrawalIndex'
	nextWithdrawalIndexStart := latestExecPayloadOffsetStart + 4
	b.NextWithdrawalIndex = capella.WithdrawalIndex(ssz.UnmarshallUint64(buf[nextWithdrawalIndexStart : nextWithdrawalIndexStart+8]))

	// Field (26) 'NextWithdrawalValidatorIndex'
	nextWithdrawalValidatorIndexStart := nextWithdrawalIndexStart + 8
	b.NextWithdrawalValidatorIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[nextWithdrawalValidatorIndexStart : nextWithdrawalValidatorIndexStart+8]))

	// Offset (27) 'HistoricalSummaries'
	historicalSummariesOffsetStart := nextWithdrawalValidatorIndexStart + 8
	o27Raw := ssz.ReadOffset(buf[historicalSummariesOffsetStart : historicalSummariesOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o27 = o27Raw + uint64(headerSizeDiff)
	} else {
		o27 = o27Raw
	}
	if o27 > size || o24 > o27 {
		return ssz.ErrOffset
	}

	// Field (28) 'DepositReceiptsStartIndex'
	depositReceiptsStartIndexStart := historicalSummariesOffsetStart + 4
	b.DepositRequestsStartIndex = ssz.UnmarshallUint64(buf[depositReceiptsStartIndexStart : depositReceiptsStartIndexStart+8])

	// Field (29) 'DepositBalanceToConsume'
	depositBalanceToConsumeStart := depositReceiptsStartIndexStart + 8
	b.DepositBalanceToConsume = phase0.Gwei(ssz.UnmarshallUint64(buf[depositBalanceToConsumeStart : depositBalanceToConsumeStart+8]))

	// Field (30) 'ExitBalanceToConsume'
	exitBalanceToConsumeStart := depositBalanceToConsumeStart + 8
	b.ExitBalanceToConsume = phase0.Gwei(ssz.UnmarshallUint64(buf[exitBalanceToConsumeStart : exitBalanceToConsumeStart+8]))

	// Field (31) 'EarliestExitEpoch'
	earliestExitEpochStart := exitBalanceToConsumeStart + 8
	b.EarliestExitEpoch = phase0.Epoch(ssz.UnmarshallUint64(buf[earliestExitEpochStart : earliestExitEpochStart+8]))

	// Field (32) 'ConsolidationBalanceToConsume'
	consolidationBalanceToConsumeStart := earliestExitEpochStart + 8
	b.ConsolidationBalanceToConsume = phase0.Gwei(ssz.UnmarshallUint64(buf[consolidationBalanceToConsumeStart : consolidationBalanceToConsumeStart+8]))

	// Field (33) 'EarliestConsolidationEpoch'
	earliestConsolidationEpochStart := consolidationBalanceToConsumeStart + 8
	b.EarliestConsolidationEpoch = phase0.Epoch(ssz.UnmarshallUint64(buf[earliestConsolidationEpochStart : earliestConsolidationEpochStart+8]))

	// Offset (34) 'PendingBalanceDeposits'
	pendingBalanceDepositsOffsetStart := earliestConsolidationEpochStart + 8
	o34Raw := ssz.ReadOffset(buf[pendingBalanceDepositsOffsetStart : pendingBalanceDepositsOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o34 = o34Raw + uint64(headerSizeDiff)
	} else {
		o34 = o34Raw
	}
	if o34 > size || o27 > o34 {
		return ssz.ErrOffset
	}

	// Offset (35) 'PendingPartialWithdrawals'
	pendingPartialWithdrawalsOffsetStart := pendingBalanceDepositsOffsetStart + 4
	o35Raw := ssz.ReadOffset(buf[pendingPartialWithdrawalsOffsetStart : pendingPartialWithdrawalsOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o35 = o35Raw + uint64(headerSizeDiff)
	} else {
		o35 = o35Raw
	}
	if o35 > size || o34 > o35 {
		return ssz.ErrOffset
	}

	// Offset (36) 'PendingConsolidations'
	pendingConsolidationsOffsetStart := pendingPartialWithdrawalsOffsetStart + 4
	o36Raw := ssz.ReadOffset(buf[pendingConsolidationsOffsetStart : pendingConsolidationsOffsetStart+4])
	if actualOffsetsStart == legacyOffsetsStart && headerSizeDiff > 0 {
		o36 = o36Raw + uint64(headerSizeDiff)
	} else {
		o36 = o36Raw
	}
	if o36 > size || o35 > o36 {
		return ssz.ErrOffset
	}

	// Field (7) 'HistoricalRoots'
	{
		buf = tail[o7:o9]
		num, err := ssz.DivideInt2(len(buf), 32, 16777216)
		if err != nil {
			return err
		}
		b.HistoricalRoots = make([]phase0.Root, num)
		for ii := 0; ii < num; ii++ {
			copy(b.HistoricalRoots[ii][:], buf[ii*32:(ii+1)*32])
		}
	}

	// Field (9) 'ETH1DataVotes'
	{
		buf = tail[o9:o11]
		num, err := ssz.DivideInt2(len(buf), 72, 2048)
		if err != nil {
			return err
		}
		b.ETH1DataVotes = make([]*phase0.ETH1Data, num)
		for ii := 0; ii < num; ii++ {
			if b.ETH1DataVotes[ii] == nil {
				b.ETH1DataVotes[ii] = new(phase0.ETH1Data)
			}
			if err = b.ETH1DataVotes[ii].UnmarshalSSZ(buf[ii*72 : (ii+1)*72]); err != nil {
				return err
			}
		}
	}

	// Field (11) 'Validators'
	{
		buf = tail[o11:o12]
		num, err := ssz.DivideInt2(len(buf), 121, 1099511627776)
		if err != nil {
			return err
		}
		b.Validators = make([]*phase0.Validator, num)
		for ii := 0; ii < num; ii++ {
			if b.Validators[ii] == nil {
				b.Validators[ii] = new(phase0.Validator)
			}
			if err = b.Validators[ii].UnmarshalSSZ(buf[ii*121 : (ii+1)*121]); err != nil {
				return err
			}
		}
	}

	// Field (12) 'Balances'
	{
		buf = tail[o12:o15]
		num, err := ssz.DivideInt2(len(buf), 8, 1099511627776)
		if err != nil {
			return err
		}
		b.Balances = make([]phase0.Gwei, num)
		for ii := 0; ii < num; ii++ {
			b.Balances[ii] = phase0.Gwei(ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8]))
		}
	}

	// Field (15) 'PreviousEpochParticipation'
	{
		buf = tail[o15:o16]
		num, err := ssz.DivideInt2(len(buf), 1, 1099511627776)
		if err != nil {
			return err
		}
		b.PreviousEpochParticipation = make([]altair.ParticipationFlags, num)
		for ii := 0; ii < num; ii++ {
			b.PreviousEpochParticipation[ii] = altair.ParticipationFlags(ssz.UnmarshallUint8(buf[ii*1 : (ii+1)*1]))
		}
	}

	// Field (16) 'CurrentEpochParticipation'
	{
		buf = tail[o16:o21]
		num, err := ssz.DivideInt2(len(buf), 1, 1099511627776)
		if err != nil {
			return err
		}
		b.CurrentEpochParticipation = make([]altair.ParticipationFlags, num)
		for ii := 0; ii < num; ii++ {
			b.CurrentEpochParticipation[ii] = altair.ParticipationFlags(ssz.UnmarshallUint8(buf[ii*1 : (ii+1)*1]))
		}
	}

	// Field (21) 'InactivityScores'
	{
		buf = tail[o21:o24]
		num, err := ssz.DivideInt2(len(buf), 8, 1099511627776)
		if err != nil {
			return err
		}
		b.InactivityScores = ssz.ExtendUint64(b.InactivityScores, num)
		for ii := 0; ii < num; ii++ {
			b.InactivityScores[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (24) 'LatestExecutionPayloadHeader'
	{
		buf = tail[o24:o27]
		if b.LatestExecutionPayloadHeader == nil {
			b.LatestExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
		}
		if err = b.LatestExecutionPayloadHeader.UnmarshalSSZ(buf); err != nil {
			return err
		}
	}

	// Field (27) 'HistoricalSummaries'
	{
		buf = tail[o27:o34]
		num, err := ssz.DivideInt2(len(buf), 64, 16777216)
		if err != nil {
			return err
		}
		b.HistoricalSummaries = make([]*capella.HistoricalSummary, num)
		for ii := 0; ii < num; ii++ {
			if b.HistoricalSummaries[ii] == nil {
				b.HistoricalSummaries[ii] = new(capella.HistoricalSummary)
			}
			if err = b.HistoricalSummaries[ii].UnmarshalSSZ(buf[ii*64 : (ii+1)*64]); err != nil {
				return err
			}
		}
	}

	// Field (34) 'PendingBalanceDeposits'
	{
		buf = tail[o34:o35]
		num, err := ssz.DivideInt2(len(buf), 192, 134217728)
		if err != nil {
			return err
		}
		b.PendingDeposits = make([]*PendingDeposit, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingDeposits[ii] == nil {
				b.PendingDeposits[ii] = new(PendingDeposit)
			}
			if err = b.PendingDeposits[ii].UnmarshalSSZ(buf[ii*192 : (ii+1)*192]); err != nil {
				return err
			}
		}
	}

	// Field (35) 'PendingPartialWithdrawals'
	{
		buf = tail[o35:o36]
		num, err := ssz.DivideInt2(len(buf), 24, 134217728)
		if err != nil {
			return err
		}
		b.PendingPartialWithdrawals = make([]*PendingPartialWithdrawal, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingPartialWithdrawals[ii] == nil {
				b.PendingPartialWithdrawals[ii] = new(PendingPartialWithdrawal)
			}
			if err = b.PendingPartialWithdrawals[ii].UnmarshalSSZ(buf[ii*24 : (ii+1)*24]); err != nil {
				return err
			}
		}
	}

	// Field (36) 'PendingConsolidations'
	{
		buf = tail[o36:]
		num, err := ssz.DivideInt2(len(buf), 16, 262144)
		if err != nil {
			return err
		}
		b.PendingConsolidations = make([]*PendingConsolidation, num)
		for ii := 0; ii < num; ii++ {
			if b.PendingConsolidations[ii] == nil {
				b.PendingConsolidations[ii] = new(PendingConsolidation)
			}
			if err = b.PendingConsolidations[ii].UnmarshalSSZ(buf[ii*16 : (ii+1)*16]); err != nil {
				return err
			}
		}
	}
	fmt.Printf("[DEBUG] BeaconState.UnmarshalSSZ: Successfully unmarshaled all fields\n")
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconState object
func (b *BeaconState) SizeSSZ() (size int) {
	size = 2736713 - phase0.LegacyBeaconBlockHeaderSize

	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(phase0.BeaconBlockHeader)
	}
	size += b.LatestBlockHeader.SizeSSZ()

	// Field (7) 'HistoricalRoots'
	size += len(b.HistoricalRoots) * 32

	// Field (9) 'ETH1DataVotes'
	size += len(b.ETH1DataVotes) * 72

	// Field (11) 'Validators'
	size += len(b.Validators) * 121

	// Field (12) 'Balances'
	size += len(b.Balances) * 8

	// Field (15) 'PreviousEpochParticipation'
	size += len(b.PreviousEpochParticipation) * 1

	// Field (16) 'CurrentEpochParticipation'
	size += len(b.CurrentEpochParticipation) * 1

	// Field (21) 'InactivityScores'
	size += len(b.InactivityScores) * 8

	// Field (24) 'LatestExecutionPayloadHeader'
	if b.LatestExecutionPayloadHeader == nil {
		b.LatestExecutionPayloadHeader = new(deneb.ExecutionPayloadHeader)
	}
	size += b.LatestExecutionPayloadHeader.SizeSSZ()

	// Field (27) 'HistoricalSummaries'
	size += len(b.HistoricalSummaries) * 64

	// Field (34) 'PendingBalanceDeposits'
	size += len(b.PendingDeposits) * 192

	// Field (35) 'PendingPartialWithdrawals'
	size += len(b.PendingPartialWithdrawals) * 24

	// Field (36) 'PendingConsolidations'
	size += len(b.PendingConsolidations) * 16

	return
}

// HashTreeRoot ssz hashes the BeaconState object
func (b *BeaconState) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconState object with a hasher
func (b *BeaconState) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'GenesisTime'
	hh.PutUint64(b.GenesisTime)

	// Field (1) 'GenesisValidatorsRoot'
	hh.PutBytes(b.GenesisValidatorsRoot[:])

	// Field (2) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	// Field (3) 'Fork'
	if b.Fork == nil {
		b.Fork = new(phase0.Fork)
	}
	if err = b.Fork.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (4) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(phase0.BeaconBlockHeader)
	}
	if err = b.LatestBlockHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (5) 'BlockRoots'
	{
		if size := len(b.BlockRoots); size != 8192 {
			err = ssz.ErrVectorLengthFn("BeaconState.BlockRoots", size, 8192)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.BlockRoots {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	// Field (6) 'StateRoots'
	{
		if size := len(b.StateRoots); size != 8192 {
			err = ssz.ErrVectorLengthFn("BeaconState.StateRoots", size, 8192)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.StateRoots {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	// Field (7) 'HistoricalRoots'
	{
		if size := len(b.HistoricalRoots); size > 16777216 {
			err = ssz.ErrListTooBigFn("BeaconState.HistoricalRoots", size, 16777216)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.HistoricalRoots {
			hh.Append(i[:])
		}
		numItems := uint64(len(b.HistoricalRoots))
		hh.MerkleizeWithMixin(subIndx, numItems, 16777216)
	}

	// Field (8) 'ETH1Data'
	if b.ETH1Data == nil {
		b.ETH1Data = new(phase0.ETH1Data)
	}
	if err = b.ETH1Data.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (9) 'ETH1DataVotes'
	{
		subIndx := hh.Index()
		num := uint64(len(b.ETH1DataVotes))
		if num > 2048 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.ETH1DataVotes {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 2048)
	}

	// Field (10) 'ETH1DepositIndex'
	hh.PutUint64(b.ETH1DepositIndex)

	// Field (11) 'Validators'
	{
		subIndx := hh.Index()
		num := uint64(len(b.Validators))
		if num > 1099511627776 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.Validators {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1099511627776)
	}

	// Field (12) 'Balances'
	{
		if size := len(b.Balances); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.Balances", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.Balances {
			hh.AppendUint64(uint64(i))
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.Balances))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 8))
	}

	// Field (13) 'RANDAOMixes'
	{
		if size := len(b.RANDAOMixes); size != 65536 {
			err = ssz.ErrVectorLengthFn("BeaconState.RANDAOMixes", size, 65536)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.RANDAOMixes {
			hh.Append(i[:])
		}
		hh.Merkleize(subIndx)
	}

	// Field (14) 'Slashings'
	{
		if size := len(b.Slashings); size != 8192 {
			err = ssz.ErrVectorLengthFn("BeaconState.Slashings", size, 8192)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.Slashings {
			hh.AppendUint64(uint64(i))
		}
		hh.Merkleize(subIndx)
	}

	// Field (15) 'PreviousEpochParticipation'
	{
		if size := len(b.PreviousEpochParticipation); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.PreviousEpochParticipation", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.PreviousEpochParticipation {
			hh.AppendUint8(uint8(i))
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.PreviousEpochParticipation))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 1))
	}

	// Field (16) 'CurrentEpochParticipation'
	{
		if size := len(b.CurrentEpochParticipation); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.CurrentEpochParticipation", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.CurrentEpochParticipation {
			hh.AppendUint8(uint8(i))
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.CurrentEpochParticipation))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 1))
	}

	// Field (17) 'JustificationBits'
	if size := len(b.JustificationBits); size != 1 {
		err = ssz.ErrBytesLengthFn("BeaconState.JustificationBits", size, 1)
		return
	}
	hh.PutBytes(b.JustificationBits)

	// Field (18) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.PreviousJustifiedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (19) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.CurrentJustifiedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (20) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(phase0.Checkpoint)
	}
	if err = b.FinalizedCheckpoint.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (21) 'InactivityScores'
	{
		if size := len(b.InactivityScores); size > 1099511627776 {
			err = ssz.ErrListTooBigFn("BeaconState.InactivityScores", size, 1099511627776)
			return
		}
		subIndx := hh.Index()
		for _, i := range b.InactivityScores {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(b.InactivityScores))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(1099511627776, numItems, 8))
	}

	// Field (22) 'CurrentSyncCommittee'
	if b.CurrentSyncCommittee == nil {
		b.CurrentSyncCommittee = new(altair.SyncCommittee)
	}
	if err = b.CurrentSyncCommittee.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (23) 'NextSyncCommittee'
	if b.NextSyncCommittee == nil {
		b.NextSyncCommittee = new(altair.SyncCommittee)
	}
	if err = b.NextSyncCommittee.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (24) 'LatestExecutionPayloadHeader'
	if err = b.LatestExecutionPayloadHeader.HashTreeRootWith(hh); err != nil {
		return
	}

	// Field (25) 'NextWithdrawalIndex'
	hh.PutUint64(uint64(b.NextWithdrawalIndex))

	// Field (26) 'NextWithdrawalValidatorIndex'
	hh.PutUint64(uint64(b.NextWithdrawalValidatorIndex))

	// Field (27) 'HistoricalSummaries'
	{
		subIndx := hh.Index()
		num := uint64(len(b.HistoricalSummaries))
		if num > 16777216 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.HistoricalSummaries {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 16777216)
	}

	// Field (28) 'DepositReceiptsStartIndex'
	hh.PutUint64(b.DepositRequestsStartIndex)

	// Field (29) 'DepositBalanceToConsume'
	hh.PutUint64(uint64(b.DepositBalanceToConsume))

	// Field (30) 'ExitBalanceToConsume'
	hh.PutUint64(uint64(b.ExitBalanceToConsume))

	// Field (31) 'EarliestExitEpoch'
	hh.PutUint64(uint64(b.EarliestExitEpoch))

	// Field (32) 'ConsolidationBalanceToConsume'
	hh.PutUint64(uint64(b.ConsolidationBalanceToConsume))

	// Field (33) 'EarliestConsolidationEpoch'
	hh.PutUint64(uint64(b.EarliestConsolidationEpoch))

	// Field (34) 'PendingBalanceDeposits'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingDeposits))
		if num > 134217728 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingDeposits {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 134217728)
	}

	// Field (35) 'PendingPartialWithdrawals'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingPartialWithdrawals))
		if num > 134217728 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingPartialWithdrawals {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 134217728)
	}

	// Field (36) 'PendingConsolidations'
	{
		subIndx := hh.Index()
		num := uint64(len(b.PendingConsolidations))
		if num > 262144 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range b.PendingConsolidations {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 262144)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BeaconState object
func (b *BeaconState) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
