// Code generated by fastssz. DO NOT EDIT.
// Hash: fa97a18404df62375826ed5ee7ded00832a9164171537b8327e9357589e54c7a
// Version: 0.1.3
package phase0

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconBlockHeader object to a target array
func (b *BeaconBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	dst = append(dst, b.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, b.StateRoot[:]...)

	// Field (4) 'BodyRoot'
	dst = append(dst, b.BodyRoot[:]...)

	// Field (5) 'ProposerTEEType'
	dst = append(dst, byte(b.ProposerTEEType))

	// Field (6) 'ProposerTEEQuote'
	dst = append(dst, b.ProposerTEEQuote[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	switch size {
	case 112:
		// Legacy header without TEE fields.
		b.Slot = Slot(ssz.UnmarshallUint64(buf[0:8]))
		b.ProposerIndex = ValidatorIndex(ssz.UnmarshallUint64(buf[8:16]))
		copy(b.ParentRoot[:], buf[16:48])
		copy(b.StateRoot[:], buf[48:80])
		copy(b.BodyRoot[:], buf[80:112])
		b.ProposerTEEType = 0
		b.ProposerTEEQuote = [ProposerTEEQuoteLength]byte{}
	case 112 + 1 + ProposerTEEQuoteLength:
		// Field (0) 'Slot'
		b.Slot = Slot(ssz.UnmarshallUint64(buf[0:8]))

		// Field (1) 'ProposerIndex'
		b.ProposerIndex = ValidatorIndex(ssz.UnmarshallUint64(buf[8:16]))

		// Field (2) 'ParentRoot'
		copy(b.ParentRoot[:], buf[16:48])

		// Field (3) 'StateRoot'
		copy(b.StateRoot[:], buf[48:80])

		// Field (4) 'BodyRoot'
		copy(b.BodyRoot[:], buf[80:112])

		// Field (5) 'ProposerTEEType'
		b.ProposerTEEType = uint8(buf[112])

		// Field (6) 'ProposerTEEQuote'
		copy(b.ProposerTEEQuote[:], buf[113:])
	default:
		return ssz.ErrSize
	}

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconBlockHeader object
func (b *BeaconBlockHeader) SizeSSZ() (size int) {
	size = 112 + 1 + ProposerTEEQuoteLength
	return
}

// HashTreeRoot ssz hashes the BeaconBlockHeader object
func (b *BeaconBlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconBlockHeader object with a hasher
func (b *BeaconBlockHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	hh.PutUint64(uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	hh.PutBytes(b.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(b.StateRoot[:])

	// Field (4) 'BodyRoot'
	hh.PutBytes(b.BodyRoot[:])

	// Field (5) 'ProposerTEEType'
	hh.PutUint64(uint64(b.ProposerTEEType))

	// Field (6) 'ProposerTEEQuote'
	hh.PutBytes(b.ProposerTEEQuote[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BeaconBlockHeader object
func (b *BeaconBlockHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
