// Code generated by fastssz. DO NOT EDIT.
// Hash: fa97a18404df62375826ed5ee7ded00832a9164171537b8327e9357589e54c7a
// Version: 0.1.3
package phase0

import (
	"fmt"

	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(b)
}

// MarshalSSZTo ssz marshals the BeaconBlockHeader object to a target array
func (b *BeaconBlockHeader) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	dst = append(dst, b.ParentRoot[:]...)

	// Field (3) 'StateRoot'
	dst = append(dst, b.StateRoot[:]...)

	// Field (4) 'BodyRoot'
	dst = append(dst, b.BodyRoot[:]...)

	// Field (5) 'ProposerTEEType'
	dst = append(dst, byte(b.ProposerTEEType))

	// Field (6) 'ProposerTEEQuote'
	dst = append(dst, b.ProposerTEEQuote[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	expectedExtendedSize := uint64(112 + 1 + ProposerTEEQuoteLength)
	fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Starting unmarshal, buffer size: %d bytes (expected: 112 or %d)\n", size, expectedExtendedSize)

	switch size {
	case 112:
		// Legacy header without TEE fields.
		fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Detected legacy header (112 bytes)\n")
		b.Slot = Slot(ssz.UnmarshallUint64(buf[0:8]))
		b.ProposerIndex = ValidatorIndex(ssz.UnmarshallUint64(buf[8:16]))
		copy(b.ParentRoot[:], buf[16:48])
		copy(b.StateRoot[:], buf[48:80])
		copy(b.BodyRoot[:], buf[80:112])
		b.ProposerTEEType = 0
		b.ProposerTEEQuote = [ProposerTEEQuoteLength]byte{}
		fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Legacy header unmarshaled - Slot: %d, ProposerIndex: %d\n", b.Slot, b.ProposerIndex)
	case 112 + 1 + ProposerTEEQuoteLength:
		// Field (0) 'Slot'
		fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Detected extended header (%d bytes)\n", size)
		b.Slot = Slot(ssz.UnmarshallUint64(buf[0:8]))

		// Field (1) 'ProposerIndex'
		b.ProposerIndex = ValidatorIndex(ssz.UnmarshallUint64(buf[8:16]))

		// Field (2) 'ParentRoot'
		copy(b.ParentRoot[:], buf[16:48])

		// Field (3) 'StateRoot'
		copy(b.StateRoot[:], buf[48:80])

		// Field (4) 'BodyRoot'
		copy(b.BodyRoot[:], buf[80:112])

		// Field (5) 'ProposerTEEType'
		b.ProposerTEEType = uint8(buf[112])
		if len(buf) < 113+ProposerTEEQuoteLength {
			fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: ERROR - Buffer too small for TEE quote, need %d bytes but have %d\n", 113+ProposerTEEQuoteLength, len(buf))
			return fmt.Errorf("buffer too small for TEE quote: need %d bytes, have %d", 113+ProposerTEEQuoteLength, len(buf))
		}

		// Field (6) 'ProposerTEEQuote'
		copy(b.ProposerTEEQuote[:], buf[113:])
		fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Extended header unmarshaled - Slot: %d, ProposerIndex: %d, TEEType: %d, TEEQuote[0:16]: %x\n",
			b.Slot, b.ProposerIndex, b.ProposerTEEType, b.ProposerTEEQuote[:16])
	default:
		fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: ERROR - Invalid size: %d (expected 112 or %d)\n", size, expectedExtendedSize)
		return ssz.ErrSize
	}

	fmt.Printf("[DEBUG] BeaconBlockHeader.UnmarshalSSZ: Successfully unmarshaled header\n")
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the BeaconBlockHeader object
func (b *BeaconBlockHeader) SizeSSZ() (size int) {
	size = 112 + 1 + ProposerTEEQuoteLength
	return
}

// HashTreeRoot ssz hashes the BeaconBlockHeader object
func (b *BeaconBlockHeader) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(b)
}

// HashTreeRootWith ssz hashes the BeaconBlockHeader object with a hasher
func (b *BeaconBlockHeader) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Slot'
	hh.PutUint64(uint64(b.Slot))

	// Field (1) 'ProposerIndex'
	hh.PutUint64(uint64(b.ProposerIndex))

	// Field (2) 'ParentRoot'
	hh.PutBytes(b.ParentRoot[:])

	// Field (3) 'StateRoot'
	hh.PutBytes(b.StateRoot[:])

	// Field (4) 'BodyRoot'
	hh.PutBytes(b.BodyRoot[:])

	// Field (5) 'ProposerTEEType'
	hh.PutUint64(uint64(b.ProposerTEEType))

	// Field (6) 'ProposerTEEQuote'
	hh.PutBytes(b.ProposerTEEQuote[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the BeaconBlockHeader object
func (b *BeaconBlockHeader) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(b)
}
